variables:
  NAME: registry.gitlab.com/azae/latex

stages:
  - build-cli
  - build-gitlab

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-cli:
  stage: build-cli
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

build-gitlab:
  stage: build-gitlab
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:gitlab --file=Dockerfile.gitlab .
    - docker push $CI_REGISTRY_IMAGE:gitlab

